#!/bin/bash

read -p "enter the directory name to check files count:" DIR

if [ ! -d "$DIR" ]; then
    echo "Error: $DIR is not a valid directory."
    exit 1
fi
A=$(find "$DIR" -maxdepth 1  -type f | wc -l)

echo "Num of files in $DIR is :- $A"
